name: rnalig
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - rdkit=2022.09.5
  - openbabel
  - mdanalysis
  - biopython=1.85
  - freesasa
  - viennarna
  - numpy=1.23.5
  - pandas=1.5.3
  - scipy=1.9.3
  - pip
  - pip:
      - py3Dmol
